# Generated by Django 3.1.7 on 2021-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoohub', '0002_qingjiaprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='qingjiaprocess',
            name='demo',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qingjiaprocess',
            name='submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qingjiaprocess',
            name='submit_note',
            field=models.CharField(default='0', max_length=150),
            preserve_default=False,
        ),
    ]
